gokrazy.go

...now that it was added there.

use WDIOC_KEEPALIVE from golang.org/x/sys/unix

---

reboot_amd64.go

The KexecFileLoad syscall wrapper and the KEXEC_* constants were added
to golang.org/x/sys/unix. Use them instead of open-coding them.

reboot: use KexecFileLoad and KEXEC_* from golang.org/x/sys/unix

---

docs/showcase/index.html
website/content/showcase.html

website: add consrv to showcase

---

gokrazy.go

This PR provides the runtime configuration for https://github.com/gokrazy/gokrazy/issues/74. 
The host part for creating the files from `gokr-packager` is still missing.

Load runtime port configuration from http(s)-port file

---

httpsredirect.go
listeners.go

Any requests with localhost as target (though not an IP address) will not be redirected. Helps with https://github.com/gokrazy/gokrazy/issues/25.
I'll send a separate PR for redirecting to the right http port (#79).

Don't redirect when localhost

---

gokrazy.go
httpsredirect.go
listeners.go

Builds on https://github.com/gokrazy/gokrazy/pull/78

Honor https-port when redirecting

---

status.go
supervise.go

Replaces https://github.com/gokrazy/gokrazy/pull/45

Provide json status api

---

go.mod
go.sum
internal/iface/iface.go

internal/iface: use unix.Ifreq APIs for IPv4 ioctls

---

supervise.go

With gokrazy/gokrazy#106, we're sending a TERM signal to service
processes and their immediate children. Service processes are being
waited on by `cmd.Wait()`, which will reap any kernel state associated
with it.  However, its child processes don't necessarily get reaped
(depending on whether its parent had time to clean up before exiting).
With this change, we explicitly wait for everything in the service
process group to exit and prevent zombies.

supervise: wait for child processes

---

docs/404.html
docs/index.html
docs/platforms/index.html
docs/prototyping/index.html
docs/quickstart/index.html
docs/showcase/index.html
docs/userguide/gpio/index.html
docs/userguide/index.html
docs/userguide/install/caddy-http-server/index.html
docs/userguide/install/index.html
docs/userguide/install/minio/index.html
docs/userguide/install/tailscale/index.html
docs/userguide/modules/index.html
docs/userguide/package-config/index.html
docs/userguide/permanent-data/index.html
docs/userguide/process-interface/index.html
docs/userguide/remotesyslog/index.html
docs/userguide/tls-for-untrusted-networks/index.html
docs/userguide/wifi/index.html
website/content/userguide/wifi.md

This pullrequest simplifies the wifi setup by using the extrafiles instead of mounting the `/perm`-partition.

Docs: configure wifi via extrafile

---

cmd/heartbeat/heartbeat.go
sbom.go

To be able to use it in other packages.

Move readSBOM to the gokrazy package

---

supervise.go
update.go

See https://github.com/gokrazy/gokrazy/issues/164.
Still to do/decide:
1) What locking is needed for `s.cmd.Args`? I'm tempted to just wrap a mutex around it (or `s.cmd`) but I haven't satisfied myself that I fully understand all the code and implications. I'd take a suggestion here.
2) I fiddled with making `divertRequest` public but that led to `updater` depending on `gokrazy`, which it doesn't yet. Same deal in the opposite direction if I declare it in the `updater` package. Should I put it in the `internal` repo or is what I have fine?
3) I'm assuming we don't need a fully backwards- and forwards-compatible migration path for the changes in each of the 3 affected repos and can just commit (I think) the `gokrazy` and `updater` changes first, then update `go.mod` in `tools` to point at …

Support passing command line flags via `gok run`

---

internal/assets/status.tmpl

dashboard: add link to raw logs

---

status.go

And cache its result, as it's called regularly by at least fbstatus, which seems like is using too much CPU. (though admittedly the fbstatus CPU problems are mostly elsewhere)
And rename mustReadFile0 because a "must" prefix implies it panics.

make Model detect QEMU, always return non-empty string

---

cmd/dhcp/dhcp.go

It might be more desirable to deploy the static network configuration as its own JSON file instead of needing to deal with string quoting it to fit into `config.json`.
- Add a simple heuristic for checking if the flag value is a JSON string.
- If the value is JSON, preserve the original behavior
- If not, treat it value as a file path and load the JSON from there.
- Set lease source string to reflect the source of static configuration.

dhcp: Allow -static_network_config to read from a file

---

website/content/quickstart/_index.markdown

Congratulations to Michael and contributors. This is a fantastic project.
Here is a small contribution I noticed while trying my first instance in macOS.

Update quickstart section with specific macOS cmd to find out about micro sd card device

---

website/content/quickstart/_index.markdown
website/content/userguide/permanent-data.markdown

I tested this in my system and works perfectly.

Add instructions to the main page to create the permanent storage filesystem in macOS.

---

website/content/packages/tailscale.md

Mention how to use gokrazy as a Tailscale subnet router and how to sign in with Tailscale SSH.

website: update tailscale package page

---

go.mod
go.sum

... to pick up changes to deviceconfig
Related to https://github.com/gokrazy/gokrazy/issues/270

Bump gokrazy/internal

---

website/content/platforms/_index.markdown
website/content/userguide/instance-config.md

Related to https://github.com/gokrazy/gokrazy/issues/270

Documentation for Rock64

---

update.go

At the moment HTTP calls to /reboot and /poweroff are blocking and need to wait for `killSupervisedServicesAndUmountPerm` to finish before returning a positive response to the caller.
This can get in the way when the caller is a supervised service running on the same gorkrazy instance.
As the caller waits for the HTTP request to get a response back, and the HTTP handler waits for all the services to be terminated. This can cause a deadlock until the supervised service is SIGKILLed after the configured deadline.
This PR introduces an async agrument that can be passed in the HTTP call as an argument (e.g. `/reboot?async=true`), which allows the HTTP handler to ack the request and return 200 OK, whilst performing the sigterm of the supervised processes (including the caller process) …

Add optional async argument to /reboot & /poweroff
