gokrazy/gokrazy

- cmd/dhcp/dhcp.go
Utsname from golang.org/x/sys/unix contains byte array members instead of
int8/uint8. This allows to simplify the NULL byte indexing in
addHostname.
> dhcp: simplify Utsname conversion

- gokrazy.go
- httpsredirect.go
- listeners.go
If there is a certificate and key in `/etc/ssl/gokrazy-web.{pem,key.pem}`, the web
interface listens and redirects to https.
This patch comes along with other patches in the [internal](https://github.com/gokrazy/internal/pull/4) and [tools](https://github.com/gokrazy/tools/pull/14) repositories.
> Added proof of concept TLS support (#7)

- assets/status.tmpl
The rationale here is that I'd typically like to know how the service is doing rather than the more static compile tie configuration. Hence important/current data on top.
> Show current messages before module info

- go.mod
- go.sum
- internal/iface/iface.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
I'm working on a safer API for ifreqs and figured I might find some use for it in gokrazy! Arguably these calls could also be replaced with rtnetlink, but this helps for now.
I want to incorporate a sockaddr version too, but I'm still working on the API for that one. Will CC you on the CL.
> internal/iface: use unix.Ifreq API for interface flags ioctl

- supervise.go
I had trouble understanding why the command (with args) I wanted to execute on gokrazy failed, because i could not see the diffrence between ['/user/echo', 'test 123'] and ['/user/echo', 'test', '123']
Output (for both examples) before:
```
2021/09/15 13:34:00 gokrazy: attempt 1, starting [/user/echo test 123]
```
Output now:
```
2021/09/15 13:34:00 gokrazy: attempt 1, starting ["/user/echo" "test" "123"]
```
> Quote and separate commands in log

- cmd/dhcp/dhcp.go
- internal/iface/iface.go
Move build constraint to internal/iface which clearly shows the Linux dependency
> dhcp: allow builds on non-64-bit architectures

- internal/assets/status.tmpl
- status.go
- supervise.go
Create a `/log` endpoint for streaming stdout/stderr logs for processes.
Replace status page stdout/stderr to call into /log to stream logs and
live update page.
> status: live tail logs

- README.md
Hey,
I added short information about how to access the permanent data on the forth partition. I could not find any documentation about this in the readme or on the website. 
I would also like to add a simple user guide for the website. How do you create the pages? I see its based on `grav`. Is there a quick start guide about how to add a new site?
Felix :)
> docs(readme): add description about accessing permanent data

- proc.go
- supervise.go
- update.go
Currently, rebooting/upgrading the instance sends a TERM signal to all
running services, waits 1 second and then reboots. Processes that take
longer to cleanly stop can't do so.
Instead, give each service up to 15s to do a clean shutdown. Reboot 15s
after the command is sent, or after all services are stopped, whichever
comes first.
To make it easier to kill entire process tree for a service, create a
per-service process group. Stopping the service can be done by sending a
single signal to the process group.
> supervise: wait for services to stop before reboot

- website/content/userguide/install/tailscale.md
Replace use of breakglass with instructions to use interactive login.
This depends on tailscale/tailscale#4117 being merged.
Add mkfs into the example so that /perm filesystem is initialized.
Add instructions how to use auth-key for unattended device auth instead
of having to use browser interactively.
Append to tailscaled/flags.txt instead of overwriting.
Clarify and update the tsnet example. Add mention of TS_AUTHKEY
as alternative here too.
> website: update Tailscale VPN documentation

- supervise.go
- website/content/userguide/process-interface.md
fixes #125
> I think we actually can do the dont-supervise-on-exit-0 change. It’s not really a case I typically have with the programs I run on gokrazy.
> For context, the platform was built for services that run indefinitely, with exit code 125 introduced initially for breakglass which should be off-by-default.
> supervisor: stop service on exit 0

- website/content/quickstart/_index.markdown
The path differs for macOS/Darwin.
Related to: https://github.com/gokrazy/internal/pull/12
Note: I had to change `<code> ... </code>` into backticks to avoid strikethrough in artifacts.
> Indicate where default password can be recovered on macOS/Darwin

- website/content/packages/showcase.markdown
Stumbled upon gokrazy the other day watching @stapelberg's video on "Why I wrote my own rsync", I immediately wanted to give it a try with the OpenTelemetry collector. *krazyotelcol* is the result of that!
Thanks for this amazing project :-)
> Add krazyotelcol to "Written for gokrazy"

- website/content/packages/showcase.markdown
This adds Restic's rest-server to the showcase.
And fixes the link to pull request to newer repository instead of older one.
> Update showcase.markdown with restic's rest-server entry

- website/config.toml
This should enable the search in the GoKrazy userguide and solves https://github.com/gokrazy/gokrazy/issues/145.
See https://learn.netlify.app/en/basics/configuration/#activate-search for further information.
I guess that you're going to re-generate the documentation as you did with in the past - which then should generate the `index.json`.
> userguide: enable search by generating index.json as output

- cmd/ntp/privdrop.go
- proc.go
- supervise.go
- update.go
Fixes #176 
I took the liberty of refacoring `killSupervisedServices` on the way:
- it sends SIGTERM to all running processes
- waits up to 15 seconds (`=signalDelay`)
- sends SIGKILL to the remaining processes
- waits up to 15 seconds (`=signalDelay`)
- returns
So that we get a higher chance of all processes having been terminated before unmount `/perm`.
(I initially replaced `syscall.Kill` with `process.Signal` and proper error checking, however rebooting always took 30s. After I while, I figured that `process.Signal` does not send the signal to the group! I reverted my changes and updated the comment :)
I have no idea how to hook this to the power button: I will let you take it from here
> implement Poweroff (and refactor around killSupervisedServices)

- internal/assets/overview.tmpl
- status.go
The current logic showing the "last log line" on the dashboard is flawed if sorting the log lines does not result in a chronological order.
Example with an empty stdout and the following stderr:
```
Hello world
A beautiful day
```
The current code sorts the lines and takes the last element. In my example, it returns `Hello world`, which is unexpected.
https://github.com/gokrazy/gokrazy/blob/ac1c5aaf638d8de41aca7c234c1c09ab61b040df/status.go#L146-L153
I have tried to fix the logic, but choosing between stderr and stdout will be lottery (as long as the timestamp is not properly recorded).
Hence I resorted to showing both, when present:
I find the result quite good, since most services are only using stderr (and when both are present, no that much space is wasted).
What do you think?
> dashboard: show latest stdout and stderr lines

- internal/assets/status.tmpl
Following #179 
I think this is the fastest logic without introducing a new state (which would keep in memory the number of lines, to prevent having to count from 0 each time).
> dashboard: refactor log line truncation logic

- cmd/dhcp/dhcp.go
On systems without an ethernet interface (like the Raspberry Pi Zero) the `dhcp` program goes into a crash loop because it can't find eth0.
This PR adds an initial loop to wait for the given interface name to appear before continuing with the rest of the program.
**NOTE**: Unfortunately I can't fully test this code because I don't have any ethernet dongle; on a plain Raspberry Pi Zero 2 W it works fine: the `dhcp` process is not crash looping anymore.
Fixes #144
> dhcp: wait indefinitely for interface to appear

- gokrazy.go
WaitForClock condition doesn't make sense to have on a Stopped service.
This change in behavior happened due to [this commit](https://github.com/gokrazy/gokrazy/commit/7e14fb215c2487a0507124e742f847dac22e1df2) which fixes the panic.
> fix waitforclock condition when creating a new service

- internal/assets/overview.tmpl
Currently the status is appended to the service status link and no label
is displayed if the service is running. The status stopped is displayed
with a warning color (yellow). To me this feels uneven and a bit chaotic
which makes it harder to get a good overview and find a service.
This does three things to improve the overview:
- Add a separate column for status label. This takes a bit of width away
from the last log line.
- Color the stopped label less aggressive (gray/default instead of
yellow/warning).
- Add a green label for running service.
Potential improvements for the future could be to show if a service is
enabled/supervised or adding actions like start/stop/restart/enable.
> Change how status is displayed

- website/content/packages/showcase.markdown
- website/content/userguide/rsync-backups.markdown
I use this project daily to store movies that I watch with my gf but since I have a gokrazy instance up and running I decided to make it possible to run in gokrazy too.
This works easily by just using a postgresql service running somewhere outside the gokrazy env.
Decided to make this as an example to the `Written for gokrazy` as this works with and without gokrazy.
> Add waiw to "Written for gokrazy"

- website/content/development/gpio.md
Feel free to update the Go code as I'm not sure if this is the best approach, but I've confirmed that it's working for my use-case and is performing reasonably well.
This PR also updates to latest `v3` `periph.io` module structure for the GPIO output example. 
Resolves #233
> docs: adds GPIO input example

- website/content/packages/prometheus.md
This goes over how to install the Prometheus server on gokrazy and how
to get the web ui working since the web assets do not get built into the
prometheus binary.
> Add documentation page on how to get Prometheus running

- website/content/_index.markdown
Go wiki was moved from GitHub to go.dev. Original link now says:
> The Go wiki on GitHub has moved to go.dev (#61940).
> Try https://go.dev/wiki/Modules or https://go.dev/wiki/.
> update go.mod replace directive link

- cmd/ntp/ntp.go
- cmd/ntp/privdrop.go
When the gokrazy deployment doesn't have internet access and the network lacks NTP traffic re-routing to the local time servers, instances may either have downright wrong clock (e.g. Raspberry Pi with no RTC) or experience divergence due to drift.
This add the ability to override the default NTP Pool Vendor Zone for gokrazy with servers supplied as command line arguments.
e.g.
```
"PackageConfig": {
"github.com/gokrazy/gokrazy/cmd/ntp": {
"CommandLineFlags": [
"time1.local" "time2.local" "10.1.2.123"
]
}
}
```
> ntp: Allow alternative NTP servers as arguments

- website/content/quickstart/_index.markdown
> Fixes wrong link in quickstart section to permanent data (macOS note section)

- mount.go
This implements the last bit of functionality for #236, using the same logic as moby/sys/mount. I added the options to the log message when they're present, omitting the text when empty.
The moby library has a `defaults` entry in the flags table for completeness, but it gets incorrectly passed down as filesystem-specific data. I decided to just remove it, since defaults are by definition the default.
To test, I built one of my instances with this branch and added an ISO mount to the qemu command I use to test on my laptop:
```
qemu-system-x86_64 \
-machine accel=kvm \
-smp 8 \
-m 2048 \
-device virtio-blk-pci,drive=hd \
-drive if=none,id=hd,file=qemu.img,format=raw \
-device virtio-blk-pci,drive=cd \
-drive if=none,id=cd,file=metadata.iso,format=raw \      <-- here
-nographic \
-netdev …
```
> Implement options for MountDevices

- docs/quickstart/index.html
- website/content/quickstart/_index.markdown
As a non-conformist, I needed to move my instances elsewhere and had to discover this variable via the code. :)
I explicitly added just the relevant parts of what Hugo generated, regenerating the entire site touches a lot of files due to changes in generation in the latest releases. If you do want to do the full rebuild I'm happy to change this PR.
The current release is also unhappy with the site in general:
```
ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.142.0. Use hugo.IsMultilingual instead.
```
I'm not sure how/if you'd like to handle this; I can open another issue if you want to track upgrading, or update the README to specify a version. Either way I figured it's out of scope for this PR.
Fixes #222.
> Document GOKRAZY_PARENT_DIR

- authenticated.go
- listeners.go
The change is made to allow other tools like [breakglass](https://github.com/gokrazy/breakglass) or [mkfs](https://github.com/gokrazy/mkfs) to interact with the Gokrazy API when TLS is enabled. The tools currently make HTTP requests to get system information or trigger reboots. When TLS is enabled, these requests fail because Gokrazy redirects all HTTP requests to HTTPS. While it is possible to configure the respective clients to properly validate (self-signed) certificates, doing so is cumbersome. Therefore, always listen on the Unix socket to avoid the complexity of certificate validation. Username and password must still be provided and will be validated.
I've considered removing the username and password validation for socket requests. However, I've decided to reverse the change and …
> Always listen on the GokrazyHTTPUnixSocket
